{"items":[

{
  "label":"MIT Physics Faculty",
  "url":"http://web.mit.edu/physics/people/faculty/index.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Directory"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"001.png",
  "views":["Tile"]
},
{
  "label":"Science Maps",
  "url":"http://scimaps.org/maps/browse/",
  "tld":"org",
  "category":["Education"],
  "purpose":["Curation"],
  "itemType":["Maps"],
  "siteType":["Organization"],
  "thumb":"002.png",
  "views":["Thumbnail"]
},
{
  "label":"MIT Physics Classes - All",
  "url":"http://web.mit.edu/physics/subjects/index.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Classes"],
  "siteType":["School"],
  "thumb":"003.png",
  "views":["Table"]
},
{
  "label":"MIT Physics Classes - Current",
  "url":"http://web.mit.edu/physics/subjects/current.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Classes"],
  "siteType":["School"],
  "thumb":"004.png",
  "views":["Table"],
},
{
  "label":"MIT Physics Classses - First Year",
  "url":"http://web.mit.edu/physics/subjects/firstyr.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Classes"],
  "siteType":["School"],
  "thumb":"005.png",
  "views":["Table"]
},
{
  "label":"Conflicts",
  "url":"http://hiik.de/exhibit_09/",
  "tld":"de",
  "category":["Politics"],
  "purpose":["Enumeration"],
  "itemType":["Events", "Conflicts"],
  "siteType":["Organization"],
  "thumb":"006.png",
  "views":["Map", "Timeline", "List"]
},
{
  "label":"City Law School Classes",
  "url":"http://www.staff.city.ac.uk/~sbbf539/bptcft/",
  "tld":"uk",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Classes"],
  "siteType":["School"],
  "thumb":"007.png",
  "views":["Timeline", "List"]
},
{
  "label":"Farmers Markets",
  "url":"http://ww2.startribune.com/projects/farmersmarkets/",
  "tld":"com",
  "category":["Commercial"],
  "purpose":["Curation"],
  "itemType":["Events", "Commercial Locations", "Markets"],
  "siteType":["News"],
  "thumb":"008.png",
  "views":["Map"]
},
{
  "label":"Kent Law Library Resources",
  "url":"http://library.kentlaw.edu/eresources/index.htm",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Curation"],
  "itemType":["Publication Sources", "Resources"],
  "siteType":["School", "Library"],
  "thumb":"009.png",
  "views":["List"]
},
{
  "label":"MIT Chemistry Faculty",
  "url":"http://web.mit.edu/cheme/people/indexi.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Directory"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"010.png",
  "views":["Table"]
},
{
  "label":"Publication List",
  "url":"http://alex.smola.org/papers.html",
  "tld":"org",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Papers", "Publications"],
  "siteType":["Personal"],
  "thumb":"011.png",
  "views":["List"]
},
{
  "label":"Columbia Law Library Resources",
  "url":"http://library.law.columbia.edu/eresources/",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Curation"],
  "itemType":["Publication Sources", "Resources"],
  "siteType":["School", "Library"],
  "thumb":"012.png",
  "views":["List"]
},
{
  "label":"Contaminated Municipalities",
  "url":"http://5lineas.com/mapas/esp-municipios-mas-contaminados.html",
  "tld":"com",
  "category":["Environment"],
  "purpose":["Curation"],
  "itemType":["Environmental"],
  "siteType":["Personal"],
  "thumb":"013.png",
  "views":["Map"]
},
{
  "label":"Composers",
  "url":"http://www.musicedmagic.com/Exhibit/composers.html",
  "tld":"com",
  "category":["Music", "Arts"],
  "purpose":["Curation"],
  "itemType":["People", "Composers"],
  "siteType":["Personal"],
  "thumb":"014.png",
  "views":["Timeline", "Map", "List"]
},
{
  "label":"Stanford Business School Alumni Groups",
  "url":"http://alumni.gsb.stanford.edu/about/alumni.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration", "Aggregation"],
  "itemType":["Groups"],
  "siteType":["School"],
  "thumb":"015.png",
  "views":["Map"]
},
{
  "label":"Floorball Matches",
  "url":"http://www.innebandycuper.se/",
  "tld":"se",
  "purpose":["Curation"],
  "category":["Sports"],
  "itemType":["Games", "Events"],
  "siteType":["Personal"],
  "thumb":"016.png",
  "views":["Timeline", "Map"]
},
{
  "label":"Personality Disorder Groups",
  "url":"http://www.personalitydisorder.org.uk/includes/exhibit-small.php",
  "tld":"uk",
  "category":["Medical"],
  "purpose":["Curation"],
  "itemType":["Resources","Groups","Places"],
  "siteType":["Organization"],
  "thumb":"017.png",
  "views":["Map", "List"]
},
{
  "label":"MIT Nobel Prize Winners",
  "url":"http://simile.mit.edu/exhibit/examples/nobelists/nobelists.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Curation"],
  "itemTpe":["People"],
  "siteType":["School"],
  "thumb":"018.png",
  "views":["Tile","List","Timeline"]
},
{
  "label":"MIT Physics Faculty",
  "url":"http://web.mit.edu/physics/research/abcp/faculty.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Directory"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"019.png",
  "views":["Tile"]
},
{
  "label":"City Law School Classes",
  "url":"http://semantic.city.ac.uk/pob/bptcft/",
  "tld":"uk",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Classes"],
  "siteType":["School"],
  "thumb":"020.png",
  "views":[]
},
{
  "label":"Accepted CVPR 2010 Conference Papers",
  "url":"http://cvl.umiacs.umd.edu/conferences/cvpr2010/results/",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Papers","Publications"],
  "siteType":["School","Conference"],
  "thumb":"021.png",
  "views":["List"]
},
{
  "label":"Education Policy and Data Center Resources",
  "url":"http://www.epdc.org/policyanalysis/default.aspx",
  "tld":"org",
  "category":["Education"],
  "purpose":["Curation"],
  "itemType":["Publications","Resources"],
  "siteType":["Organization"],
  "thumb":"022.png",
  "views":["List", "Table"]
},
{
  "label":"Peyre Publications",
  "url":"http://www.ceremade.dauphine.fr/~peyre/publications/",
  "tld":"fr",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Papers","Publications"],
  "siteType":["Personal"],
  "thumb":"023.png",
  "views":["List"]
},
{
  "label":"Pappalardo Fellows Directory",
  "url":"http://web.mit.edu/physics/people/pappalardo/index.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"024.png",
  "views":["Table"]
},
{
  "label":"Bay Area Foreclosures",
  "url":"http://www.sfgate.com/maps/foreclosures/",
  "tld":"com",
  "category":["Real Estate","Finance"],
  "purpose":["Enumeration"],
  "itemType":["Foreclosures"],
  "siteType":["News"],
  "thumb":"025.png",
  "views":["Map"]
},
{
  "label":"MIT Physics Administrators",
  "url":"http://web.mit.edu/physics/people/admin/index.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"026.png",
  "views":["Table"]
},
{
  "label":"City Populations in Spain",
  "url":"http://5lineas.com/mapas/esp-municipios-mas-50mil.html",
  "tld":"com",
  "category":["Government"],
  "purposes":["Enumeration"],
  "itemType":["Cities"],
  "siteType":["Personal"],
  "thumb":"027.png",
  "views":["Map", "Table"]
},
{
  "label":"Beethoven Timeline",
  "url":"http://www.musicedmagic.com/Exhibit/beethoventimeline.html",
  "tld":"com",
  "category":["Music", "Arts"],
  "purposes":["Curation"],
  "itemType":["Events"],
  "siteType":["Personal"],
  "thumb":"028.png",
  "views":["List", "Timeline"]
},
{
  "label":"Projects",
  "url":"http://www.plantsci.cam.ac.uk/grads/selecting.html",
  "tld":"uk",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Projects"],
  "siteType":["School"],
  "thumb":"029.png",
  "views":["List"]
},
{
  "label":"Bay Area Foreclosures - 2009 Q2",
  "url":"http://www.sfgate.com/maps/foreclosures/2009q2/",
  "tld":"com",
  "category":["Real Estate", "Finance"],
  "purpose":["Enumeration"],
  "itemType":["Foreclosures"],
  "siteType":["News"],
  "thumb":"030.png",
  "views":["Map"]
},
{
  "label":"Veggie Guide to Glasgow",
  "url":"http://gvn.rhizomatics.org.uk/glasgowguide.html",
  "tld":"uk",
  "category":["Food"],
  "purpose":["Curation"],
  "itemType":["Restaurants"],
  "siteType":["Personal"],
  "thumb":"031.png",
  "views":["Map"]
},
{
  "label":"Dance Classes",
  "url":"http://dancedigital.org.uk/classes/find-a-course/",
  "tld":"uk",
  "category":["Arts", "Dance"],
  "purpose":["Enumeration"],
  "itemType":["Classes"],
  "siteType":["Organization"],
  "thumb":"032.png",
  "views":["Tile", "Map"]
},
{
  "label":"Factory Portland - Musicians",
  "url":"http://www.factoryportland.com/musicsearch/musicians/",
  "tld":"com",
  "category":["Arts", "Music"],
  "purpose":["Curation"],
  "itemType":["People"],
  "siteType":["Commercial",
  "thumb":"033.png",
  "views":["Table"]
},
{
  "label":"Factory Portland - Businesses",
  "url":"http://www.factoryportland.com/musicsearch/businesses/",
  "tld":"com",
  "category":["Arts", "Music"],
  "purpose":["Curation"],
  "itemType":["Companies"],
  "siteType":["Commercial"],
  "thumb":"034.png",
  "views":["Table"]
},
{
  "label":"Rating Minnesota's Bridges",
  "url":"http://ww2.startribune.com/projects/maps/bridges/bridges.html",
  "tld":"com",
  "category":["Government"],
  "purpose":["Enumeration"],
  "itemType":["Bridges"],
  "siteType":["News"],
  "thumb":"035.png",
  "views":["Map"]
},
{
  "label":"Medieval and Early Modern Manuscripts",
  "url":"http://scriptorium.english.cam.ac.uk/manuscripts/",
  "tld":"uk",
  "category":["Education", "History"],
  "purpose":["Curation"],
  "itemType":["Publications", "Manuscripts"],
  "siteType":["School"],
  "thumb":"036.png",
  "views":["List"]
},
{
  "label":"Fellows at Cornell",
  "url":"http://www.sustainablefuture.cornell.edu/people/fellows/fellows-browse.php",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"037.png",
  "views":["Tile"]
},
{
  "label":"Choice and Medication Health Clinics",
  "url":"http://choiceandmedication.org/cms/subscribers/",
  "tld":"org",
  "category":["Medical"],
  "purpose":["Curation"],
  "itemType":["Clinics", "Places"],
  "siteType":["Organization"],
  "thumb":"038.png",
  "views":["List", "Map"]
},
{
  "label":"Pennsylvania School District Map",
  "url":"http://www.swingingsammy.com/schools/20082009_MV-PI_AR.html",
  "tld":"com",
  "category":["Government", "Education"],
  "purpose":["Exposition"],
  "itemType":["Districts"],
  "siteType":["Personal"],
  "thumb":"039.png",
  "views":["Table", "Map"]
},
{
  "label":"Jewish Study Resources on the Web",
  "url":"http://fc.gannacademy.org/gannopedia/ganntools/index.html",
  "tld":"org",
  "category":["Education","Religion"],
  "purpose":["Curation"],
  "itemType":["Resources"],
  "siteType":["Organization"],
  "thumb":"040.png",
  "views":["Table"]
},
{
  "label":"Artists of History",
  "url":"http://swiki.hfbk-hamburg.de:8888/seminare/uploads/156/ZeitstrahlEpochen_Test.html",
  "tld":"de",
  "category":["Arts", "Art"],
  "purpose":["Enumeration"],
  "itemType":["People"],
  "siteType":["Organization"],
  "thumb":"041.png",
  "views":["Timeline", "List"]
},
{
  "label":"Balcombe's Publications",
  "url":"http://www.plantsci.cam.ac.uk/research/baulcombe/publications.html",
  "tld":"uk",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Publications", "Papers"],
  "siteType":["Personal"],
  "thumb":"042.png",
  "views":["List"]
},
{
  "label":"Gretton's Publications",
  "url":"http://www.gatsby.ucl.ac.uk/~gretton/pubs.html",
  "tld":"uk",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["Publications", "Papers"],
  "siteType":["Personal"],
  "thumb":"043.png",
  "views":["List"]
},
{
  "label":"Thesis Project Deliverables",
  "url":"http://theses.mit.edu/FACADE/CALTRANS/exhibit/cut7/",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Exposition", "Project Management"],
  "itemType":["Deliverables"],
  "siteType":["Personal"],
  "thumb":"044.png",
  "views":["Tile", "Table", "Timeline"]
},
{
  "label":"Open Data Directory - Datasets",
  "url":"http://open.mflask.com/datasets",
  "tld":"com",
  "category":["Open Data"],
  "purpose":["Curation"],
  "itemType":["Data Sets"],
  "siteType":["Organization"],
  "thumb":"045.png",
  "views":["List"]
},
{
  "label":"More Artists of History",
  "url":"http://swiki.hfbk-hamburg.de:8888/seminare/uploads/156/KunstEpochen.html",
  "tld":"de",
  "category":["Arts", "Art"],
  "purpose":["Enumeration"],
  "itemType":["People"],
  "siteType":["Organization"],
  "thumb":"046.png",
  "views":["Timeline", "List"]
},
{
  "label":"Haystack Group Members",
  "url":"http://groups.csail.mit.edu/haystack/people.html",
  "tld":"edu",
  "category":["Education"],
  "purpose":["Enumeration"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"047.png",
  "views":["Tile", "Timeline"]
},
{
  "label":"MIT Experimental Nuclear and Particle Physics Faculty",
  "url":"http://web.mit.edu/physics/research/npx/faculty.html",
  "tld":"edu",
  "purpose":["Enumeration"],
  "category":["Education"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"048.png",
  "views":["Table"]
},
{
  "label":"Seattle Central Faculty",
  "id":"http://seattlecentral.edu/faculty/jcrump/timeline.html",
  "tld":"edu",
  "purpose":["Enumeration"],
  "category":["Education"],
  "itemType":["People"],
  "siteType":["School"],
  "thumb":"049.png",
  "views":["Timeline", "Map"]
}  
]}
